server:
  port: 44333
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ghttlab.com:3306/ciyu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ciyu
    password: CiyuConquersAll
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: localhost:9200
#    username: ciyu
#    password: CiyuConquersAll
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    # 取消文件上传大小限制
    multipart:
      max-file-size: -1
      max-request-size: -1
logging:
  level:
    tracer: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace
springdoc:
  api-docs:
    path: /api-docs

qiniu:
  kodo:
    accessKey: FtMmroBvlYFVFViYQXsQzdloWbL8XAyOX8ZN_JFn
    secretKey: QSrdEZch3D0rNEuC4-q_TSH4Nc0MWetgWQUTjQvE
    bucket: shortvideospace
    domain: s3iz4iflg.bkt.clouddn.com
  file:
    # 上传短视频文件允许的扩展名
    allowed: avi, mp4, mpg, wmv, mov, flv
